
// ════════════════════════════════════════════════════════════════
// MULTILINGUAL SUPPORT — KO / EN / TC
// ════════════════════════════════════════════════════════════════
const STRINGS = {
ko:{
  pageTitle:'북중미 월드컵과 함께하는 MIDAS API 최신 기술 체험하기',
  headerH1:'북중미 월드컵과 함께하는 MIDAS API 최신 기술 체험하기',
  headerMeta:'절단 정이십면체(축구공) 구조물 자동 생성 &nbsp;·&nbsp; 개발자: Dennis &nbsp;·&nbsp; v{ver} ({date} 업데이트)',
  step1:'제품 선택',step2:'API 연결',step3:'파라미터',step4:'경계 조건',step5:'하중',
  step6:'3D 미리보기',step7:'모델 생성',step8:'해석',step9:'무료체험신청',
  sidebarEyebrow:'MIDAS API Experience',
  sidebarH2:'이 체험에서<br>무엇을 할 수 있나요?',
  sidebarDesc:'<strong style="color:#c7d2fe">MIDAS Gen NX / Civil NX의 Open API</strong>를 활용해,<br>브라우저에서 직접 축구공(절단 정이십면체) 구조물을 생성 —<br><strong style="color:#c7d2fe">자동 생성 → 해석 → 결과 시각화</strong>까지<br>단계별로 체험합니다.',
  flow1:'① 제품 선택',flow2:'② API 연결',flow3:'③ 파라미터',flow4:'④ 경계&amp;하중',
  flow5:'⑤ 3D 미리보기',flow6:'⑥ 모델 생성',flow7:'⑦ 해석 실행',flow8:'⑧ 결과 확인',
  nudgeTitle:'API 연결 정보가 없다구요?',
  nudgeDesc:'지금 바로 무료체험판을 신청하고 API Key를 받아보세요!',
  nudgeBtn:'무료체험신청 →',
  wcEyebrow:'FIFA World Cup 2026 · 북중미',
  wcH2:'🏆 폐막식 &amp; 결승전',
  wcLabel1:'폐막식 Closing Ceremony',wcDate1:'2026년 7월 19일 (일)',
  wcKst1:'결승전 직전 진행',wcVenue:'MetLife Stadium, 미국 뉴저지 East Rutherford',
  wcLabel2:'결승전 Final',wcDate2:'2026년 7월 20일 (월) 04:00 KST',
  wcKst2:'현지: 7월 19일 (일) 15:00 ET',
  cdLabel:'⏱ 결승전까지 남은 시간 (KST 기준)',cdInit:'계산 중...',cdKickoff:'결승 킥오프!🎉',
  step1H2:'🎯 제품 선택',step1Desc:'축구공 구조물을 생성할 MIDAS 소프트웨어를 선택하세요.',
  genNXDesc:'건축 구조 전문 해석 소프트웨어<br>비선형 · 내진 · 성능 기반 설계<br>API 기반 자동화 워크플로우',
  genNXBadge:'건축 구조',
  civilNXDesc:'교량 · 토목 구조 해석 소프트웨어<br>3차원 · 시공 단계 · PSC 해석<br>API 기반 자동화 워크플로우',
  civilNXBadge:'교량・토목',
  confirmBtn:'확인 →',selectFirst:'먼저 소프트웨어를 선택하세요.',
  step2H2Suffix:'API 연결 정보',mapiPlaceholder:'MAPI Key를 입력하세요',baseUrlLabel:'Base URL (기본값 자동 입력, 수정 가능)',
  showHideKey:'키 보기/숨기기',testConn:'연결 테스트 →',backBtn:'← 이전',
  enterBothAlert:'MAPI Key를 입력하세요.',testingConn:'연결 테스트 중...',
  connSuccess:'✅ 연결 성공! 다음 단계로 이동합니다.',
  connFail:'❌ 연결 확인 실패: {status}',
  connDisconnected:'❌ {prog} 프로그램이 실행/연결되어 있지 않습니다. 프로그램을 켠 뒤 다시 시도하세요. (키는 정상)',
  connMismatch:'❌ 제품 불일치: 이 키는 {key} 용입니다 (현재 선택: {sel}). 제품 선택을 바꾸세요.',
  connError:'❌ 연결 오류: {msg}',
  step3H2:'📐 구조물 파라미터',secSize:'구조물 크기',lblRadius:'반경 (mm)',
  lblCx:'중심 X (mm)',lblCy:'중심 Y (mm)',lblCz:'중심 Z (mm)',
  secMaterial:'재료 (강재)',lblMatName:'재료명',lblElast:'탄성계수 (MPa)',
  lblPoisn:'포아송 비',lblDen:'밀도 (N/mm³)',
  secSection:'단면 (직사각형)',lblSectName:'단면명',lblSectH:'높이 H (mm)',lblSectB:'너비 B (mm)',
  nextBtn:'다음 →',
  step4H2:'🔒 경계 조건 (지지)',secSupNode:'지지 절점 선택',
  nodeAuto:'자동 (최하단 절점)',nodeManual:'수동 (직접 입력)',
  nodeAutoDesc:'반경·중심 Z 기준으로 <strong>가장 아래 위치한 절점들</strong>을 자동으로 선택합니다.',
  lblManualNodes:'절점 번호 (쉼표로 구분, 예: 1,5,9)',secSupType:'지지 타입',
  supFixName:'고정단',supPinName:'힌지 (핀)',supRolName:'롤러 (Z)',supCustName:'사용자 정의',
  supCustDesc:'DOF 직접 선택',selectDOF:'구속할 DOF를 선택하세요',
  dofDx:'Dx (X 이동)',dofDy:'Dy (Y 이동)',dofDz:'Dz (Z 이동)',
  dofRx:'Rx (X 회전)',dofRy:'Ry (Y 회전)',dofRz:'Rz (Z 회전)',
  step5H2:'⬇️ 하중 설정',addLCBtn:'+ 하중 케이스 추가',previewBtn:'미리보기 →',
  lcBadgeLabel:'하중 케이스',deleteBtn:'삭제',lblLCName:'<label>하중 케이스명</label>',
  lblLCType:'<label>하중 분류</label>',
  lcOptUser:'USER (사용자 정의)',lcOptD:'D (고정하중)',lcOptL:'L (활하중)',
  lcOptW:'W (풍하중)',lcOptE:'E (지진하중)',lcLoadKind:'하중 종류',
  tagSW:'자중 (Self-weight)',tagNL:'절점 하중 (Nodal)',
  lblDirection:'<label>방향</label>',swDirZ:'-Z (중력 방향)',
  lblScale:'<label>계수</label>',nlAll:'전체 절점',nlBottom:'최하단 절점',nlManual:'직접 입력',
  lblNLNodes:'<label style="font-size:.79rem;color:#666">절점 번호 (쉼표 구분)</label>',
  step6H2:'🔍 3D 미리보기',metricNodes:'절점',metricBeams:'보 요소',metricRadius:'반경 (mm)',
  genModelBtn:'모델 생성 →',
  step7H2:'🚀 모델 생성',step7Suffix:'모델 생성',
  clearLabel:'기존 절점 / 요소 / 재료 / 단면 / 경계조건 / 하중 초기화 후 생성',
  genBtnLbl:'⚽ 축구공 생성 시작',
  logInit:'▶ 생성 버튼을 눌러 시작하세요.',
  noticeTitle:'화면이 업데이트되지 않았다면?',
  hintShortcutTitle:'단축키',hintShortcutDesc:'<code>Ctrl + A</code><br>전체 선택 → 뷰 갱신',
  hintMouseTitle:'마우스',hintMouseDesc:'뷰포트에서<br>스크롤 or 드래그',
  hintMenuTitle:'메뉴',hintMenuDesc:'View → Fit All<br>(전체 보기)',
  toAnalBtnLbl:'해석 실행 →',
  traceName3dEdge:'요소 (90)',traceName3dNode:'절점 (60)',
  traceSup:'지지 절점 ({n})',traceLoad:'하중 절점 ({n})',
  step8H2anal:'⚡ 해석 실행',step8H2result:'📊 해석 결과',
  badgeWait:'⏸ 해석 대기 중',badgeRun:'🔄 해석 실행 중...',badgeDone:'✅ 해석 완료',badgeErr:'❌ 해석 오류',
  runAnalBtnLbl:'🔬 해석 시작',
  alogInit:'▶ 해석 버튼을 눌러 분석을 시작하세요. (모델이 먼저 생성되어 있어야 합니다)',
  lblLoadCase:'하중 케이스',
  tabReact:'반력 (Reactions)',tabDisp:'변위 (Displacement)',tabMember:'부재력 (Internal Forces)',
  tabShear:'전단력 (Shear Force)',tabMoment:'휨모멘트 (Bending Moment)',
  tabTorsion:'비틀림 (Torsional Moment)',tabStress:'응력비 (Stress Ratio / DCR)',
  startOverBtn:'🔄 처음부터',freeTrialBtn:'무료체험신청 →',
  logInit5:'초기화 중...',logCleared:'기존 데이터 초기화 완료',logMat15:'재료 생성 중...',
  logMatFail:'재료 실패: {msg}',logMatOk:'재료: {name}',logSect25:'단면 생성 중...',
  logSectFail:'단면 실패: {msg}',logSectOk:'단면: {name} ({h}×{b} mm)',
  logNode38:'절점 생성 중...',logNodeFail:'절점 실패: {msg}',logNodeOk:'절점 {n}개 생성',
  logElem52:'요소 생성 중...',logElemFail:'요소 실패: {msg}',logElemOk:'보 요소 {n}개 생성',
  logBC65:'경계 조건 생성 중...',logBCFail:'경계조건 실패: {msg}',
  logBCOk:'경계 조건 {n}개 절점 ({label})',logBCNone:'경계 조건: 없음',
  logLoad78:'하중 생성 중...',logLC:'하중 케이스: [{type}] {name}',
  logSWFail:'자중 실패: {msg}',logSWOk:'  자중 ({dir} × {val})',
  logNLFail:'절점 하중 실패: {msg}',logNLOk:'  절점 하중 {n}개 절점 (Fz={fz} N)',
  logNLNone:'  절점 하중: 대상 없음',logDone:'완료!',
  logModelOk:'🎉 {name} 모델 생성 완료!',logError:'오류: {msg}',
  alogUnits:'단위 설정 중 (N, MM)...',alogUnitsOk:'단위 설정 완료',
  alogRunning:'해석 실행 중... (완료 시까지 대기)',analFailed:'해석 실패',alogDone:'해석 완료',
  alogFetchLC:'결과 조회 중 ({n}개 하중 케이스)...',
  alogReact:'반력 조회 중...',alogReactOk:'반력: {n}행',alogReactNone:'반력 데이터 없음',
  alogDisp:'변위 조회 중...',alogDispOk:'변위: {n}행',alogDispNone:'변위 데이터 없음',
  alogForce:'부재력 (BEAMFORCE) 조회 중...',alogForceOk:'부재력: {n}행',alogForceNone:'부재력 데이터 없음',
  alogStress:'응력비 (BEAMSTRESS) 조회 중...',alogStressOk:'응력비: {n}행',
  alogStressNone:'응력비 데이터 없음 (설계 미수행 시 정상)',
  alogStressSkip:'응력비 조회 생략 ({msg})',alogAllDone:'🎉 해석 및 결과 조회 완료!',
  alogError:'오류: {msg}',
  statSupNodeCount:'지지 절점 수',chartReact:'반력 Fz (N) - 지지 절점별',xaxisNode:'절점 번호',
  statMaxDisp:'Max 합성변위 (mm)',chartDisp:'Dz 변위 Top 20 (mm)',
  statMemberCount:'부재 수',chartAxial:'부재력 Fx Top 20 (N)',xaxisElem:'요소 번호',
  statMaxShear:'Max 전단합 (N)',chartShear:'전단력 Top 20 (|Fy| 기준)',yaxisShear:'전단 (N)',
  chartMoment:'휨모멘트 Top 20 (|Mz| 기준)',yaxisMoment:'모멘트 (N·mm)',
  noTorsion:'비틀림 데이터(Mx) 없음',chartTorsion:'비틀림 Mx Top 20 (N·mm)',
  noStress:'응력비 데이터 없음 (설계 체크 미수행 또는 API 미지원)',
  statMaxStress:'Max 응력비',statAvgStress:'평균 응력비',
  statOverStress:'초과 부재 (>1.0)',statTotalMember:'총 부재 수',
  stressName:'응력비',chartStress:'응력비 Top 20',yaxisStress:'응력비',
  supFixLabel:'고정단 (Dx Dy Dz Rx Ry Rz)',supPinLabel:'힌지 (Dx Dy Dz)',
  supRolLabel:'롤러-Z (Dz)',supCustLabel:'사용자 정의: ',
  sumSupLabel:'<b>지지 조건:</b> ',sumNodeAuto:'최하단 절점 자동 선택',sumNodeManual:'수동 입력 ─ ',
  sumNodeLabel:'<b>절점 선택:</b> ',
  step9Headline:'지금 바로 MIDAS를<br>무료로 체험해 보세요!',
  step9Sub:'방금 직접 생성하고 해석한 축구공 구조물처럼,<br>MIDAS Gen NX · Civil NX로 당신의 아이디어를 현실로 만드세요.',
  step9CTA:'무료체험 신청하기 →',
  tf1Desc:'건축 구조 전문 해석 소프트웨어<br>비선형 · 내진 · 성능 기반 설계<br>API 기반 자동화 워크플로우',
  tf2Desc:'교량 · 토목 구조 해석 소프트웨어<br>3차원 · 시공 단계 · PSC 해석<br>API 기반 자동화 워크플로우',
  tf3Desc:'REST API로 모델 생성부터<br>해석 실행 · 결과 추출까지<br>완전 자동화 가능',
  tsStep1:'무료체험 신청',tsStep2:'이메일 인증',tsStep3:'소프트웨어 다운로드',tsStep4:'즉시 사용 시작',
  tlBtn1:'🎁 무료 체험 신청 (Free Trial)',tlBtn2:'🌐 MIDAS 공식 홈페이지',
  step9BackBtn:'← 이전',
},
en:{
  pageTitle:'Experience the Latest MIDAS API Technology with the 2026 World Cup',
  headerH1:'Experience the Latest MIDAS API Technology with the 2026 World Cup',
  headerMeta:'Automated Truncated Icosahedron Structure Generation &nbsp;·&nbsp; Developer: Dennis &nbsp;·&nbsp; v{ver} (Updated {date})',
  step1:'Product',step2:'API Connect',step3:'Parameters',step4:'Boundary',step5:'Loads',
  step6:'3D Preview',step7:'Generate',step8:'Analysis',step9:'Free Trial',
  sidebarEyebrow:'MIDAS API Experience',
  sidebarH2:'What can you experience<br>in this demo?',
  sidebarDesc:'<strong style="color:#c7d2fe">Leveraging the Open API of MIDAS Gen NX / Civil NX</strong>,<br>generate a soccer ball (truncated icosahedron) structure<br>directly in your browser — from <strong style="color:#c7d2fe">auto-generation → analysis → result visualization</strong><br>step by step.',
  flow1:'① Product',flow2:'② API Connect',flow3:'③ Parameters',flow4:'④ Boundary &amp; Loads',
  flow5:'⑤ 3D Preview',flow6:'⑥ Generate Model',flow7:'⑦ Run Analysis',flow8:'⑧ View Results',
  nudgeTitle:'No API credentials yet?',
  nudgeDesc:'Sign up for a free trial now and get your API Key instantly!',
  nudgeBtn:'Free Trial →',
  wcEyebrow:'FIFA World Cup 2026 · North America',
  wcH2:'🏆 Closing Ceremony &amp; Final',
  wcLabel1:'Closing Ceremony',wcDate1:'July 19, 2026 (Sun)',
  wcKst1:'Held right before the Final',wcVenue:'MetLife Stadium, East Rutherford, NJ, USA',
  wcLabel2:'Final',wcDate2:'Jul 20, 2026 (Mon) 04:00 KST',
  wcKst2:'Local: Jul 19 (Sun) 15:00 ET',
  cdLabel:'⏱ Time Until the Final (KST)',cdInit:'Calculating...',cdKickoff:'FINAL KICKOFF!🎉',
  step1H2:'🎯 Select Your Software',step1Desc:'Select the MIDAS software to build your soccer ball structure.',
  genNXDesc:'Building Structural Analysis<br>Nonlinear &amp; Seismic Design<br>Performance-Based Design',
  genNXBadge:'Building Structure',
  civilNXDesc:'Bridge &amp; Civil Structural Analysis<br>3D &amp; Construction Stage Analysis<br>Prestressed Concrete Analysis',
  civilNXBadge:'Civil &amp; Bridge',
  confirmBtn:'Confirm Selection →',selectFirst:'Please select a software first.',
  step2H2Suffix:'API Connection',mapiPlaceholder:'Enter your MAPI Key',baseUrlLabel:'Base URL (default pre-filled, editable)',
  showHideKey:'Show/Hide Key',testConn:'Test Connection →',backBtn:'← Back',
  enterBothAlert:'Please enter your MAPI Key.',testingConn:'Testing connection...',
  connSuccess:'✅ Connection successful! Proceeding to next step.',
  connFail:'❌ Connection check failed: {status}',
  connDisconnected:'❌ {prog} is not running / connected. Launch the program and try again. (Key is valid)',
  connMismatch:'❌ Product mismatch: this key is for {key} (currently selected: {sel}). Change the product selection.',
  connError:'❌ Connection error: {msg}',
  step3H2:'📐 Structure Parameters',secSize:'Structure Size',lblRadius:'Radius (mm)',
  lblCx:'Center X (mm)',lblCy:'Center Y (mm)',lblCz:'Center Z (mm)',
  secMaterial:'Material (Steel)',lblMatName:'Material Name',lblElast:'Elastic Modulus (MPa)',
  lblPoisn:"Poisson's Ratio",lblDen:'Density (N/mm³)',
  secSection:'Section (Rectangular)',lblSectName:'Section Name',lblSectH:'Height H (mm)',lblSectB:'Width B (mm)',
  nextBtn:'Next →',
  step4H2:'🔒 Boundary Conditions (Supports)',secSupNode:'Support Node Selection',
  nodeAuto:'Auto (Bottom nodes)',nodeManual:'Manual (direct input)',
  nodeAutoDesc:'Automatically selects the <strong>lowest nodes</strong> based on radius and center Z.',
  lblManualNodes:'Node numbers (comma-separated, e.g. 1,5,9)',secSupType:'Support Type',
  supFixName:'Fixed',supPinName:'Hinge (Pin)',supRolName:'Roller (Z)',supCustName:'Custom',
  supCustDesc:'Select DOFs',selectDOF:'Select DOFs to restrain',
  dofDx:'Dx (X Translation)',dofDy:'Dy (Y Translation)',dofDz:'Dz (Z Translation)',
  dofRx:'Rx (X Rotation)',dofRy:'Ry (Y Rotation)',dofRz:'Rz (Z Rotation)',
  step5H2:'⬇️ Load Settings',addLCBtn:'+ Add Load Case',previewBtn:'Preview →',
  lcBadgeLabel:'Load Case',deleteBtn:'Delete',
  lblLCName:'<label>Load Case Name</label>',lblLCType:'<label>Load Type</label>',
  lcOptUser:'USER (User defined)',lcOptD:'D (Dead load)',lcOptL:'L (Live load)',
  lcOptW:'W (Wind load)',lcOptE:'E (Seismic load)',lcLoadKind:'Load type',
  tagSW:'Self-weight',tagNL:'Nodal load',
  lblDirection:'<label>Direction</label>',swDirZ:'-Z (Gravity)',
  lblScale:'<label>Scale Factor</label>',nlAll:'All nodes',nlBottom:'Bottom nodes',nlManual:'Manual input',
  lblNLNodes:'<label style="font-size:.79rem;color:#666">Node numbers (comma-separated)</label>',
  step6H2:'🔍 3D Preview',metricNodes:'Nodes',metricBeams:'Beam Elements',metricRadius:'Radius (mm)',
  genModelBtn:'Generate Model →',
  step7H2:'🚀 Generate Model',step7Suffix:'Model Generation',
  clearLabel:'Clears existing nodes / elements / materials / sections / boundary conditions / loads',
  genBtnLbl:'⚽ Start Generating Soccer Ball',
  logInit:'▶ Press the Generate button to start.',noticeTitle:'Screen not updated?',
  hintShortcutTitle:'Shortcut',hintShortcutDesc:'<code>Ctrl + A</code><br>Select All → Refresh view',
  hintMouseTitle:'Mouse',hintMouseDesc:'In viewport:<br>Scroll or drag',
  hintMenuTitle:'Menu',hintMenuDesc:'View → Fit All',
  toAnalBtnLbl:'Run Analysis →',
  traceName3dEdge:'Elements (90)',traceName3dNode:'Nodes (60)',
  traceSup:'Support nodes ({n})',traceLoad:'Load nodes ({n})',
  step8H2anal:'⚡ Run Analysis',step8H2result:'📊 Analysis Results',
  badgeWait:'⏸ Waiting',badgeRun:'🔄 Running...',badgeDone:'✅ Complete',badgeErr:'❌ Error',
  runAnalBtnLbl:'🔬 Start Analysis',
  alogInit:'▶ Click the Analyze button to start. (Model must be generated first)',
  lblLoadCase:'Load Case',
  tabReact:'Reactions',tabDisp:'Displacement',tabMember:'Internal Forces',
  tabShear:'Shear Force',tabMoment:'Bending Moment',tabTorsion:'Torsional Moment',
  tabStress:'Stress Ratio / DCR',
  startOverBtn:'🔄 Start Over',freeTrialBtn:'Free Trial →',
  logInit5:'Initializing...',logCleared:'Existing data cleared',logMat15:'Creating material...',
  logMatFail:'Material failed: {msg}',logMatOk:'Material: {name}',logSect25:'Creating section...',
  logSectFail:'Section failed: {msg}',logSectOk:'Section: {name} ({h}×{b} mm)',
  logNode38:'Creating nodes...',logNodeFail:'Node creation failed: {msg}',logNodeOk:'Created {n} nodes',
  logElem52:'Creating elements...',logElemFail:'Element creation failed: {msg}',logElemOk:'Created {n} beam elements',
  logBC65:'Creating boundary conditions...',logBCFail:'Boundary condition failed: {msg}',
  logBCOk:'Boundary conditions: {n} nodes ({label})',logBCNone:'Boundary conditions: none',
  logLoad78:'Creating loads...',logLC:'Load case: [{type}] {name}',
  logSWFail:'Self-weight failed: {msg}',logSWOk:'  Self-weight ({dir} × {val})',
  logNLFail:'Nodal load failed: {msg}',logNLOk:'  Nodal loads: {n} nodes (Fz={fz} N)',
  logNLNone:'  Nodal loads: no target nodes',logDone:'Done!',
  logModelOk:'🎉 {name} model generated!',logError:'Error: {msg}',
  alogUnits:'Setting units (N, MM)...',alogUnitsOk:'Units set',
  alogRunning:'Running analysis... (waiting for completion)',analFailed:'Analysis failed',alogDone:'Analysis complete',
  alogFetchLC:'Fetching results ({n} load cases)...',
  alogReact:'Fetching reactions...',alogReactOk:'Reactions: {n} rows',alogReactNone:'No reaction data',
  alogDisp:'Fetching displacements...',alogDispOk:'Displacements: {n} rows',alogDispNone:'No displacement data',
  alogForce:'Fetching internal forces (BEAMFORCE)...',alogForceOk:'Internal forces: {n} rows',alogForceNone:'No internal force data',
  alogStress:'Fetching stress ratio (BEAMSTRESS)...',alogStressOk:'Stress ratio: {n} rows',
  alogStressNone:'No stress ratio data (normal if design check not run)',
  alogStressSkip:'Stress ratio fetch skipped ({msg})',alogAllDone:'🎉 Analysis and result retrieval complete!',
  alogError:'Error: {msg}',
  statSupNodeCount:'Support node count',chartReact:'Reaction Fz (N) by support node',xaxisNode:'Node No.',
  statMaxDisp:'Max resultant displacement (mm)',chartDisp:'Dz Displacement Top 20 (mm)',
  statMemberCount:'Member count',chartAxial:'Axial Force Fx Top 20 (N)',xaxisElem:'Element No.',
  statMaxShear:'Max shear resultant (N)',chartShear:'Shear Force Top 20 (|Fy|)',yaxisShear:'Shear (N)',
  chartMoment:'Bending Moment Top 20 (|Mz|)',yaxisMoment:'Moment (N·mm)',
  noTorsion:'No torsion data (Mx)',chartTorsion:'Torsion Mx Top 20 (N·mm)',
  noStress:'No stress ratio data (design check not run or not supported)',
  statMaxStress:'Max stress ratio',statAvgStress:'Avg stress ratio',
  statOverStress:'Over-limit members (>1.0)',statTotalMember:'Total members',
  stressName:'Stress Ratio',chartStress:'Stress Ratio Top 20',yaxisStress:'Stress Ratio',
  supFixLabel:'Fixed (Dx Dy Dz Rx Ry Rz)',supPinLabel:'Hinge (Dx Dy Dz)',
  supRolLabel:'Roller-Z (Dz)',supCustLabel:'Custom: ',
  sumSupLabel:'<b>Support:</b> ',sumNodeAuto:'Auto bottom nodes',sumNodeManual:'Manual — ',
  sumNodeLabel:'<b>Node selection:</b> ',
  step9Headline:'Try MIDAS for Free<br>Right Now!',
  step9Sub:'Just like the soccer ball structure you just created and analyzed,<br>turn your ideas into reality with MIDAS Gen NX · Civil NX.',
  step9CTA:'Apply for Free Trial →',
  tf1Desc:'Structural analysis for buildings<br>Nonlinear · Seismic · Performance-based design<br>API-driven automation workflow',
  tf2Desc:'Bridge &amp; civil structure analysis<br>3D · Construction stage · PSC analysis<br>API-driven automation workflow',
  tf3Desc:'From model creation via REST API<br>to analysis &amp; result extraction —<br>fully automatable',
  tsStep1:'Apply for Free Trial',tsStep2:'Email Verification',tsStep3:'Download Software',tsStep4:'Start Using Immediately',
  tlBtn1:'🎁 Apply for Free Trial',tlBtn2:'🌐 MIDAS Official Website',
  step9BackBtn:'← Back',
},
tc:{
  pageTitle:'與2026北中美世界盃一起體驗MIDAS API最新技術',
  headerH1:'與2026北中美世界盃一起體驗MIDAS API最新技術',
  headerMeta:'截角二十面體（足球）結構自動生成 &nbsp;·&nbsp; 開發者：Dennis &nbsp;·&nbsp; v{ver} ({date} 更新)',
  step1:'選擇產品',step2:'API連線',step3:'參數設定',step4:'邊界條件',step5:'載重設定',
  step6:'3D預覽',step7:'建立模型',step8:'分析',step9:'免費試用',
  sidebarEyebrow:'MIDAS API 體驗',
  sidebarH2:'這個示範<br>能體驗什麼？',
  sidebarDesc:'<strong style="color:#c7d2fe">利用 MIDAS Gen NX / Civil NX 的開放 API</strong>，<br>直接在瀏覽器中生成足球（截角二十面體）結構——<br>從 <strong style="color:#c7d2fe">自動生成 → 分析 → 結果視覺化</strong>，<br>逐步完成。',
  flow1:'① 選擇產品',flow2:'② API連線',flow3:'③ 參數設定',flow4:'④ 邊界&amp;載重',
  flow5:'⑤ 3D預覽',flow6:'⑥ 建立模型',flow7:'⑦ 執行分析',flow8:'⑧ 查看結果',
  nudgeTitle:'尚未取得API憑證？',
  nudgeDesc:'立即申請免費試用，馬上取得您的 API Key！',
  nudgeBtn:'免費試用申請 →',
  wcEyebrow:'FIFA世界盃 2026 · 北中美',
  wcH2:'🏆 閉幕典禮 &amp; 決賽',
  wcLabel1:'閉幕典禮',wcDate1:'2026年7月19日（日）',
  wcKst1:'決賽前舉行',wcVenue:'美國紐澤西州東盧瑟福 MetLife Stadium',
  wcLabel2:'決賽',wcDate2:'2026年7月20日（一）03:00 CST',
  wcKst2:'當地時間：7月19日（日）15:00 ET',
  cdLabel:'⏱ 距決賽倒數（台灣時間 CST）',cdInit:'計算中...',cdKickoff:'決賽開踢！🎉',
  step1H2:'🎯 選擇您的軟體',step1Desc:'請選擇要建立足球結構的 MIDAS 軟體。',
  genNXDesc:'建築結構專業分析軟體<br>非線性・耐震・性能設計<br>API 自動化工作流程',
  genNXBadge:'建築結構',
  civilNXDesc:'橋樑・土木結構分析軟體<br>三維・施工階段・PSC 分析<br>API 自動化工作流程',
  civilNXBadge:'橋樑・土木',
  confirmBtn:'確認選擇 →',selectFirst:'請先選擇軟體。',
  step2H2Suffix:'API 連線',mapiPlaceholder:'請輸入 MAPI Key',baseUrlLabel:'Base URL (預設自動帶入，可修改)',
  showHideKey:'顯示/隱藏金鑰',testConn:'連線測試 →',backBtn:'← 上一步',
  enterBothAlert:'請輸入您的 MAPI Key。',testingConn:'連線測試中...',
  connSuccess:'✅ 連線成功！即將進入下一步。',
  connFail:'❌ 連線確認失敗：{status}',
  connDisconnected:'❌ {prog} 程式未啟動／未連線。請開啟程式後再試一次。（金鑰正常）',
  connMismatch:'❌ 產品不符：此金鑰為 {key} 用（目前選擇：{sel}）。請更改產品選擇。',
  connError:'❌ 連線錯誤：{msg}',
  step3H2:'📐 結構參數',secSize:'結構尺寸',lblRadius:'半徑 (mm)',
  lblCx:'中心 X (mm)',lblCy:'中心 Y (mm)',lblCz:'中心 Z (mm)',
  secMaterial:'材料（鋼材）',lblMatName:'材料名稱',lblElast:'彈性模數 (MPa)',
  lblPoisn:'浦松比',lblDen:'密度 (N/mm³)',
  secSection:'斷面（矩形）',lblSectName:'斷面名稱',lblSectH:'高度 H (mm)',lblSectB:'寬度 B (mm)',
  nextBtn:'下一步 →',
  step4H2:'🔒 邊界條件（支承）',secSupNode:'支承節點選擇',
  nodeAuto:'自動（最底部節點）',nodeManual:'手動（直接輸入）',
  nodeAutoDesc:'依據半徑與中心 Z，自動選取<strong>最底部節點</strong>。',
  lblManualNodes:'節點編號（逗號分隔，例：1,5,9）',secSupType:'支承類型',
  supFixName:'固定端',supPinName:'鉸接（Pin）',supRolName:'滾接支承（Z）',supCustName:'自定義',
  supCustDesc:'選擇自由度',selectDOF:'請選擇要束制的自由度',
  dofDx:'Dx（X方向平移）',dofDy:'Dy（Y方向平移）',dofDz:'Dz（Z方向平移）',
  dofRx:'Rx（X軸旋轉）',dofRy:'Ry（Y軸旋轉）',dofRz:'Rz（Z軸旋轉）',
  step5H2:'⬇️ 載重設定',addLCBtn:'+ 新增載重工況',previewBtn:'預覽 →',
  lcBadgeLabel:'載重工況',deleteBtn:'刪除',
  lblLCName:'<label>載重工況名稱</label>',lblLCType:'<label>載重類型</label>',
  lcOptUser:'USER（使用者自定義）',lcOptD:'D（靜載重）',lcOptL:'L（活載重）',
  lcOptW:'W（風載重）',lcOptE:'E（地震載重）',lcLoadKind:'載重種類',
  tagSW:'自重',tagNL:'節點載重',
  lblDirection:'<label>方向</label>',swDirZ:'-Z（重力方向）',
  lblScale:'<label>係數</label>',nlAll:'全部節點',nlBottom:'最底部節點',nlManual:'手動輸入',
  lblNLNodes:'<label style="font-size:.79rem;color:#666">節點編號（逗號分隔）</label>',
  step6H2:'🔍 3D 預覽',metricNodes:'節點數',metricBeams:'梁元素數',metricRadius:'半徑 (mm)',
  genModelBtn:'建立模型 →',
  step7H2:'🚀 建立模型',step7Suffix:'建立模型',
  clearLabel:'生成前清除現有節點 / 元素 / 材料 / 斷面 / 邊界條件 / 載重',
  genBtnLbl:'⚽ 開始生成足球結構',
  logInit:'▶ 請按「建立模型」按鈕開始。',noticeTitle:'畫面未更新？',
  hintShortcutTitle:'快捷鍵',hintShortcutDesc:'<code>Ctrl + A</code><br>全選 → 更新視圖',
  hintMouseTitle:'滑鼠',hintMouseDesc:'在視埠中：<br>滾輪或拖曳',
  hintMenuTitle:'選單',hintMenuDesc:'View → Fit All',
  toAnalBtnLbl:'執行分析 →',
  traceName3dEdge:'梁元素 (90)',traceName3dNode:'節點 (60)',
  traceSup:'支承節點 ({n})',traceLoad:'載重節點 ({n})',
  step8H2anal:'⚡ 執行分析',step8H2result:'📊 分析結果',
  badgeWait:'⏸ 等待中',badgeRun:'🔄 分析中...',badgeDone:'✅ 完成',badgeErr:'❌ 錯誤',
  runAnalBtnLbl:'🔬 開始分析',
  alogInit:'▶ 請按「開始分析」按鈕。（請先完成模型建立）',
  lblLoadCase:'載重工況',
  tabReact:'反力',tabDisp:'位移',tabMember:'內力',
  tabShear:'剪力',tabMoment:'彎矩',tabTorsion:'扭矩',tabStress:'應力比 / DCR',
  startOverBtn:'🔄 重新開始',freeTrialBtn:'免費試用申請 →',
  logInit5:'初始化中...',logCleared:'已清除現有資料',logMat15:'建立材料中...',
  logMatFail:'材料建立失敗：{msg}',logMatOk:'材料：{name}',logSect25:'建立斷面中...',
  logSectFail:'斷面建立失敗：{msg}',logSectOk:'斷面：{name} ({h}×{b} mm)',
  logNode38:'建立節點中...',logNodeFail:'節點建立失敗：{msg}',logNodeOk:'已建立 {n} 個節點',
  logElem52:'建立元素中...',logElemFail:'元素建立失敗：{msg}',logElemOk:'已建立 {n} 個梁元素',
  logBC65:'建立邊界條件中...',logBCFail:'邊界條件建立失敗：{msg}',
  logBCOk:'邊界條件：{n} 個節點（{label}）',logBCNone:'邊界條件：無',
  logLoad78:'建立載重中...',logLC:'載重工況：[{type}] {name}',
  logSWFail:'自重建立失敗：{msg}',logSWOk:'  自重（{dir} × {val}）',
  logNLFail:'節點載重建立失敗：{msg}',logNLOk:'  節點載重：{n} 個節點（Fz={fz} N）',
  logNLNone:'  節點載重：無目標節點',logDone:'完成！',
  logModelOk:'🎉 {name} 模型建立完成！',logError:'錯誤：{msg}',
  alogUnits:'設定單位 (N, MM)...',alogUnitsOk:'單位設定完成',
  alogRunning:'分析執行中...（等待完成）',analFailed:'分析失敗',alogDone:'分析完成',
  alogFetchLC:'擷取結果中（{n} 個載重工況）...',
  alogReact:'擷取反力中...',alogReactOk:'反力：{n} 筆資料',alogReactNone:'無反力資料',
  alogDisp:'擷取位移中...',alogDispOk:'位移：{n} 筆資料',alogDispNone:'無位移資料',
  alogForce:'擷取內力 (BEAMFORCE)...',alogForceOk:'內力：{n} 筆資料',alogForceNone:'無內力資料',
  alogStress:'擷取應力比 (BEAMSTRESS)...',alogStressOk:'應力比：{n} 筆資料',
  alogStressNone:'無應力比資料（未執行設計檢核時為正常）',
  alogStressSkip:'應力比擷取略過（{msg}）',alogAllDone:'🎉 分析及結果擷取完成！',
  alogError:'錯誤：{msg}',
  statSupNodeCount:'支承節點數',chartReact:'反力 Fz (N) — 各支承節點',xaxisNode:'節點編號',
  statMaxDisp:'最大合成位移 (mm)',chartDisp:'Dz 位移 Top 20 (mm)',
  statMemberCount:'構件數',chartAxial:'軸力 Fx Top 20 (N)',xaxisElem:'元素編號',
  statMaxShear:'最大剪力合力 (N)',chartShear:'剪力 Top 20 (|Fy|)',yaxisShear:'剪力 (N)',
  chartMoment:'彎矩 Top 20 (|Mz|)',yaxisMoment:'彎矩 (N·mm)',
  noTorsion:'無扭矩資料 (Mx)',chartTorsion:'扭矩 Mx Top 20 (N·mm)',
  noStress:'無應力比資料（未執行設計檢核或 API 不支援）',
  statMaxStress:'最大應力比',statAvgStress:'平均應力比',
  statOverStress:'超限構件 (>1.0)',statTotalMember:'構件總數',
  stressName:'應力比',chartStress:'應力比 Top 20',yaxisStress:'應力比',
  supFixLabel:'固定端 (Dx Dy Dz Rx Ry Rz)',supPinLabel:'鉸接 (Dx Dy Dz)',
  supRolLabel:'滾接支承-Z (Dz)',supCustLabel:'自定義：',
  sumSupLabel:'<b>支承：</b>',sumNodeAuto:'自動（最底部節點）',sumNodeManual:'手動 — ',
  sumNodeLabel:'<b>節點選擇：</b>',
  step9Headline:'立即免費體驗<br>MIDAS！',
  step9Sub:'就像您剛才親手建立並分析的足球結構，<br>用 MIDAS Gen NX · Civil NX 將您的設計構想化為現實。',
  step9CTA:'免費試用申請 →',
  tf1Desc:'建築結構專業分析軟體<br>非線性・耐震・性能設計<br>API 自動化工作流程',
  tf2Desc:'橋樑・土木結構分析軟體<br>三維・施工階段・PSC 分析<br>API 自動化工作流程',
  tf3Desc:'透過 REST API 自動完成<br>模型建立・分析執行・結果擷取<br>全流程自動化',
  tsStep1:'申請免費試用',tsStep2:'電子郵件驗證',tsStep3:'下載軟體',tsStep4:'立即開始使用',
  tlBtn1:'🎁 免費試用申請',tlBtn2:'🌐 MIDAS 官方網站',
  step9BackBtn:'← 上一步',
},
ja:{
  pageTitle:'2026 ワールドカップとともに体験する MIDAS API 最新技術',
  headerH1:'2026 ワールドカップとともに体験する MIDAS API 最新技術',
  headerMeta:'切頂二十面体（サッカーボール）構造の自動生成 &nbsp;·&nbsp; 開発者：Dennis &nbsp;·&nbsp; v{ver} ({date} 更新)',
  step1:'製品選択',step2:'API接続',step3:'パラメータ',step4:'境界条件',step5:'荷重',
  step6:'3Dプレビュー',step7:'モデル生成',step8:'解析',step9:'無料体験',
  sidebarEyebrow:'MIDAS API 体験',
  sidebarH2:'このデモで<br>何が体験できる？',
  sidebarDesc:'<strong style="color:#c7d2fe">MIDAS Gen NX / Civil NX のオープン API</strong>を活用し、<br>ブラウザ上でサッカーボール（切頂二十面体）構造を生成 —<br><strong style="color:#c7d2fe">自動生成 → 解析 → 結果の可視化</strong>まで<br>ステップごとに体験します。',
  flow1:'① 製品選択',flow2:'② API接続',flow3:'③ パラメータ',flow4:'④ 境界&amp;荷重',
  flow5:'⑤ 3Dプレビュー',flow6:'⑥ モデル生成',flow7:'⑦ 解析実行',flow8:'⑧ 結果確認',
  nudgeTitle:'API 接続情報をお持ちでない方へ',
  nudgeDesc:'今すぐ無料体験版を申し込んで API Key を取得しましょう！',
  nudgeBtn:'無料体験申込 →',
  wcEyebrow:'FIFA ワールドカップ 2026 · 北中米',
  wcH2:'🏆 閉会式 &amp; 決勝',
  wcLabel1:'閉会式',wcDate1:'2026年7月19日（日）',
  wcKst1:'決勝の直前に実施',wcVenue:'米国ニュージャージー州イーストラザフォード MetLife Stadium',
  wcLabel2:'決勝',wcDate2:'2026年7月20日（月）04:00 JST',
  wcKst2:'現地時間：7月19日（日）15:00 ET',
  cdLabel:'⏱ 決勝までのカウントダウン（日本時間 JST）',cdInit:'計算中...',cdKickoff:'決勝キックオフ！🎉',
  step1H2:'🎯 ソフトウェアを選択',step1Desc:'サッカーボール構造を生成する MIDAS ソフトウェアを選択してください。',
  genNXDesc:'建築構造専門の解析ソフトウェア<br>非線形・耐震・性能設計<br>API ベースの自動化ワークフロー',
  genNXBadge:'建築構造',
  civilNXDesc:'橋梁・土木構造の解析ソフトウェア<br>3次元・施工段階・PSC 解析<br>API ベースの自動化ワークフロー',
  civilNXBadge:'橋梁・土木',
  confirmBtn:'選択を確定 →',selectFirst:'先にソフトウェアを選択してください。',
  step2H2Suffix:'API 接続',mapiPlaceholder:'MAPI Key を入力してください',baseUrlLabel:'Base URL（デフォルト自動入力・編集可）',
  showHideKey:'キーの表示/非表示',testConn:'接続テスト →',backBtn:'← 戻る',
  enterBothAlert:'MAPI Key を入力してください。',testingConn:'接続テスト中...',
  connSuccess:'✅ 接続成功！次のステップへ進みます。',
  connFail:'❌ 接続確認に失敗：{status}',
  connDisconnected:'❌ {prog} が起動／接続されていません。プログラムを起動してから再試行してください。（キーは正常）',
  connMismatch:'❌ 製品が一致しません：このキーは {key} 用です（現在の選択：{sel}）。製品選択を変更してください。',
  connError:'❌ 接続エラー：{msg}',
  step3H2:'📐 構造パラメータ',secSize:'構造サイズ',lblRadius:'半径 (mm)',
  lblCx:'中心 X (mm)',lblCy:'中心 Y (mm)',lblCz:'中心 Z (mm)',
  secMaterial:'材料（鋼材）',lblMatName:'材料名',lblElast:'弾性係数 (MPa)',
  lblPoisn:'ポアソン比',lblDen:'密度 (N/mm³)',
  secSection:'断面（矩形）',lblSectName:'断面名',lblSectH:'高さ H (mm)',lblSectB:'幅 B (mm)',
  nextBtn:'次へ →',
  step4H2:'🔒 境界条件（支持）',secSupNode:'支持節点の選択',
  nodeAuto:'自動（最下部の節点）',nodeManual:'手動（直接入力）',
  nodeAutoDesc:'半径・中心 Z に基づいて<strong>最下部の節点</strong>を自動選択します。',
  lblManualNodes:'節点番号（カンマ区切り、例：1,5,9）',secSupType:'支持タイプ',
  supFixName:'固定',supPinName:'ヒンジ（ピン）',supRolName:'ローラー（Z）',supCustName:'カスタム',
  supCustDesc:'自由度を選択',selectDOF:'拘束する自由度を選択してください',
  dofDx:'Dx（X 並進）',dofDy:'Dy（Y 並進）',dofDz:'Dz（Z 並進）',
  dofRx:'Rx（X 回転）',dofRy:'Ry（Y 回転）',dofRz:'Rz（Z 回転）',
  step5H2:'⬇️ 荷重設定',addLCBtn:'+ 荷重ケースを追加',previewBtn:'プレビュー →',
  lcBadgeLabel:'荷重ケース',deleteBtn:'削除',
  lblLCName:'<label>荷重ケース名</label>',lblLCType:'<label>荷重タイプ</label>',
  lcOptUser:'USER（ユーザー定義）',lcOptD:'D（死荷重）',lcOptL:'L（活荷重）',
  lcOptW:'W（風荷重）',lcOptE:'E（地震荷重）',lcLoadKind:'荷重の種類',
  tagSW:'自重',tagNL:'節点荷重',
  lblDirection:'<label>方向</label>',swDirZ:'-Z（重力方向）',
  lblScale:'<label>係数</label>',nlAll:'全節点',nlBottom:'最下部の節点',nlManual:'手動入力',
  lblNLNodes:'<label style="font-size:.79rem;color:#666">節点番号（カンマ区切り）</label>',
  step6H2:'🔍 3D プレビュー',metricNodes:'節点数',metricBeams:'梁要素数',metricRadius:'半径 (mm)',
  genModelBtn:'モデル生成 →',
  step7H2:'🚀 モデル生成',step7Suffix:'モデル生成',
  clearLabel:'生成前に既存の節点 / 要素 / 材料 / 断面 / 境界条件 / 荷重をクリア',
  genBtnLbl:'⚽ サッカーボール生成を開始',
  logInit:'▶「モデル生成」ボタンを押して開始してください。',noticeTitle:'画面が更新されない場合は？',
  hintShortcutTitle:'ショートカット',hintShortcutDesc:'<code>Ctrl + A</code><br>全選択 → ビュー更新',
  hintMouseTitle:'マウス',hintMouseDesc:'ビューポート内で：<br>スクロールまたはドラッグ',
  hintMenuTitle:'メニュー',hintMenuDesc:'View → Fit All',
  toAnalBtnLbl:'解析実行 →',
  traceName3dEdge:'要素 (90)',traceName3dNode:'節点 (60)',
  traceSup:'支持節点 ({n})',traceLoad:'荷重節点 ({n})',
  step8H2anal:'⚡ 解析実行',step8H2result:'📊 解析結果',
  badgeWait:'⏸ 待機中',badgeRun:'🔄 解析中...',badgeDone:'✅ 完了',badgeErr:'❌ エラー',
  runAnalBtnLbl:'🔬 解析開始',
  alogInit:'▶「解析開始」ボタンを押してください。（先にモデルを生成しておく必要があります）',
  lblLoadCase:'荷重ケース',
  tabReact:'反力',tabDisp:'変位',tabMember:'部材力',
  tabShear:'せん断力',tabMoment:'曲げモーメント',tabTorsion:'ねじりモーメント',tabStress:'応力比 / DCR',
  startOverBtn:'🔄 最初から',freeTrialBtn:'無料体験申込 →',
  logInit5:'初期化中...',logCleared:'既存データをクリアしました',logMat15:'材料を作成中...',
  logMatFail:'材料の作成に失敗：{msg}',logMatOk:'材料：{name}',logSect25:'断面を作成中...',
  logSectFail:'断面の作成に失敗：{msg}',logSectOk:'断面：{name} ({h}×{b} mm)',
  logNode38:'節点を作成中...',logNodeFail:'節点の作成に失敗：{msg}',logNodeOk:'{n} 個の節点を作成',
  logElem52:'要素を作成中...',logElemFail:'要素の作成に失敗：{msg}',logElemOk:'{n} 個の梁要素を作成',
  logBC65:'境界条件を作成中...',logBCFail:'境界条件の作成に失敗：{msg}',
  logBCOk:'境界条件：{n} 節点（{label}）',logBCNone:'境界条件：なし',
  logLoad78:'荷重を作成中...',logLC:'荷重ケース：[{type}] {name}',
  logSWFail:'自重の作成に失敗：{msg}',logSWOk:'  自重（{dir} × {val}）',
  logNLFail:'節点荷重の作成に失敗：{msg}',logNLOk:'  節点荷重：{n} 節点（Fz={fz} N）',
  logNLNone:'  節点荷重：対象なし',logDone:'完了！',
  logModelOk:'🎉 {name} モデルの生成が完了！',logError:'エラー：{msg}',
  alogUnits:'単位を設定中 (N, MM)...',alogUnitsOk:'単位設定完了',
  alogRunning:'解析を実行中...（完了までお待ちください）',analFailed:'解析に失敗',alogDone:'解析完了',
  alogFetchLC:'結果を取得中（{n} 荷重ケース）...',
  alogReact:'反力を取得中...',alogReactOk:'反力：{n} 行',alogReactNone:'反力データなし',
  alogDisp:'変位を取得中...',alogDispOk:'変位：{n} 行',alogDispNone:'変位データなし',
  alogForce:'部材力 (BEAMFORCE) を取得中...',alogForceOk:'部材力：{n} 行',alogForceNone:'部材力データなし',
  alogStress:'応力比 (BEAMSTRESS) を取得中...',alogStressOk:'応力比：{n} 行',
  alogStressNone:'応力比データなし（設計チェック未実行時は正常）',
  alogStressSkip:'応力比の取得をスキップ（{msg}）',alogAllDone:'🎉 解析および結果取得が完了！',
  alogError:'エラー：{msg}',
  statSupNodeCount:'支持節点数',chartReact:'反力 Fz (N) — 支持節点別',xaxisNode:'節点番号',
  statMaxDisp:'最大合成変位 (mm)',chartDisp:'Dz 変位 Top 20 (mm)',
  statMemberCount:'部材数',chartAxial:'軸力 Fx Top 20 (N)',xaxisElem:'要素番号',
  statMaxShear:'最大せん断合力 (N)',chartShear:'せん断力 Top 20 (|Fy|)',yaxisShear:'せん断 (N)',
  chartMoment:'曲げモーメント Top 20 (|Mz|)',yaxisMoment:'モーメント (N·mm)',
  noTorsion:'ねじりデータなし (Mx)',chartTorsion:'ねじり Mx Top 20 (N·mm)',
  noStress:'応力比データなし（設計チェック未実行または API 非対応）',
  statMaxStress:'最大応力比',statAvgStress:'平均応力比',
  statOverStress:'超過部材 (>1.0)',statTotalMember:'部材総数',
  stressName:'応力比',chartStress:'応力比 Top 20',yaxisStress:'応力比',
  supFixLabel:'固定 (Dx Dy Dz Rx Ry Rz)',supPinLabel:'ヒンジ (Dx Dy Dz)',
  supRolLabel:'ローラー-Z (Dz)',supCustLabel:'カスタム：',
  sumSupLabel:'<b>支持条件：</b>',sumNodeAuto:'最下部の節点を自動選択',sumNodeManual:'手動入力 — ',
  sumNodeLabel:'<b>節点選択：</b>',
  step9Headline:'今すぐ MIDAS を<br>無料で体験！',
  step9Sub:'今あなたが生成して解析したサッカーボール構造のように、<br>MIDAS Gen NX · Civil NX であなたのアイデアを実現しましょう。',
  step9CTA:'無料体験を申し込む →',
  tf1Desc:'建築構造専門の解析ソフトウェア<br>非線形・耐震・性能設計<br>API ベースの自動化ワークフロー',
  tf2Desc:'橋梁・土木構造の解析ソフトウェア<br>3次元・施工段階・PSC 解析<br>API ベースの自動化ワークフロー',
  tf3Desc:'REST API でモデル生成から<br>解析実行・結果抽出まで<br>完全に自動化可能',
  tsStep1:'無料体験を申込',tsStep2:'メール認証',tsStep3:'ソフトウェアをダウンロード',tsStep4:'すぐに利用開始',
  tlBtn1:'🎁 無料体験を申込',tlBtn2:'🌐 MIDAS 公式サイト',
  step9BackBtn:'← 戻る',
},
sc:{
  pageTitle:'与2026北中美世界杯一起体验MIDAS API最新技术',
  headerH1:'与2026北中美世界杯一起体验MIDAS API最新技术',
  headerMeta:'截角二十面体（足球）结构自动生成 &nbsp;·&nbsp; 开发者：Dennis &nbsp;·&nbsp; v{ver} ({date} 更新)',
  step1:'选择产品',step2:'API连接',step3:'参数设置',step4:'边界条件',step5:'荷载设置',
  step6:'3D预览',step7:'创建模型',step8:'分析',step9:'免费试用',
  sidebarEyebrow:'MIDAS API 体验',
  sidebarH2:'这个示例<br>能体验什么？',
  sidebarDesc:'<strong style="color:#c7d2fe">利用 MIDAS Gen NX / Civil NX 的开放 API</strong>，<br>直接在浏览器中生成足球（截角二十面体）结构——<br>从 <strong style="color:#c7d2fe">自动生成 → 分析 → 结果可视化</strong>，<br>逐步完成。',
  flow1:'① 选择产品',flow2:'② API连接',flow3:'③ 参数设置',flow4:'④ 边界&amp;荷载',
  flow5:'⑤ 3D预览',flow6:'⑥ 创建模型',flow7:'⑦ 执行分析',flow8:'⑧ 查看结果',
  nudgeTitle:'尚未取得API凭证？',
  nudgeDesc:'立即申请免费试用，马上获取您的 API Key！',
  nudgeBtn:'免费试用申请 →',
  wcEyebrow:'FIFA世界杯 2026 · 北中美',
  wcH2:'🏆 闭幕典礼 &amp; 决赛',
  wcLabel1:'闭幕典礼',wcDate1:'2026年7月19日（日）',
  wcKst1:'决赛前举行',wcVenue:'美国新泽西州东卢瑟福 MetLife Stadium',
  wcLabel2:'决赛',wcDate2:'2026年7月20日（一）03:00 CST',
  wcKst2:'当地时间：7月19日（日）15:00 ET',
  cdLabel:'⏱ 距决赛倒计时（北京时间 CST）',cdInit:'计算中...',cdKickoff:'决赛开球！🎉',
  step1H2:'🎯 选择您的软件',step1Desc:'请选择要创建足球结构的 MIDAS 软件。',
  genNXDesc:'建筑结构专业分析软件<br>非线性・抗震・性能设计<br>API 自动化工作流程',
  genNXBadge:'建筑结构',
  civilNXDesc:'桥梁・土木结构分析软件<br>三维・施工阶段・PSC 分析<br>API 自动化工作流程',
  civilNXBadge:'桥梁・土木',
  confirmBtn:'确认选择 →',selectFirst:'请先选择软件。',
  step2H2Suffix:'API 连接',mapiPlaceholder:'请输入 MAPI Key',baseUrlLabel:'Base URL (默认自动填入，可修改)',
  showHideKey:'显示/隐藏密钥',testConn:'连接测试 →',backBtn:'← 上一步',
  enterBothAlert:'请输入您的 MAPI Key。',testingConn:'连接测试中...',
  connSuccess:'✅ 连接成功！即将进入下一步。',
  connFail:'❌ 连接确认失败：{status}',
  connDisconnected:'❌ {prog} 程序未启动／未连接。请打开程序后再试一次。（密钥正常）',
  connMismatch:'❌ 产品不符：此密钥为 {key} 用（当前选择：{sel}）。请更改产品选择。',
  connError:'❌ 连接错误：{msg}',
  step3H2:'📐 结构参数',secSize:'结构尺寸',lblRadius:'半径 (mm)',
  lblCx:'中心 X (mm)',lblCy:'中心 Y (mm)',lblCz:'中心 Z (mm)',
  secMaterial:'材料（钢材）',lblMatName:'材料名称',lblElast:'弹性模量 (MPa)',
  lblPoisn:'泊松比',lblDen:'密度 (N/mm³)',
  secSection:'截面（矩形）',lblSectName:'截面名称',lblSectH:'高度 H (mm)',lblSectB:'宽度 B (mm)',
  nextBtn:'下一步 →',
  step4H2:'🔒 边界条件（支承）',secSupNode:'支承节点选择',
  nodeAuto:'自动（最底部节点）',nodeManual:'手动（直接输入）',
  nodeAutoDesc:'依据半径与中心 Z，自动选取<strong>最底部节点</strong>。',
  lblManualNodes:'节点编号（逗号分隔，例：1,5,9）',secSupType:'支承类型',
  supFixName:'固定端',supPinName:'铰接（Pin）',supRolName:'滚动支承（Z）',supCustName:'自定义',
  supCustDesc:'选择自由度',selectDOF:'请选择要约束的自由度',
  dofDx:'Dx（X方向平移）',dofDy:'Dy（Y方向平移）',dofDz:'Dz（Z方向平移）',
  dofRx:'Rx（X轴旋转）',dofRy:'Ry（Y轴旋转）',dofRz:'Rz（Z轴旋转）',
  step5H2:'⬇️ 荷载设置',addLCBtn:'+ 新增荷载工况',previewBtn:'预览 →',
  lcBadgeLabel:'荷载工况',deleteBtn:'删除',
  lblLCName:'<label>荷载工况名称</label>',lblLCType:'<label>荷载类型</label>',
  lcOptUser:'USER（用户自定义）',lcOptD:'D（恒载）',lcOptL:'L（活载）',
  lcOptW:'W（风荷载）',lcOptE:'E（地震荷载）',lcLoadKind:'荷载种类',
  tagSW:'自重',tagNL:'节点荷载',
  lblDirection:'<label>方向</label>',swDirZ:'-Z（重力方向）',
  lblScale:'<label>系数</label>',nlAll:'全部节点',nlBottom:'最底部节点',nlManual:'手动输入',
  lblNLNodes:'<label style="font-size:.79rem;color:#666">节点编号（逗号分隔）</label>',
  step6H2:'🔍 3D 预览',metricNodes:'节点数',metricBeams:'梁单元数',metricRadius:'半径 (mm)',
  genModelBtn:'创建模型 →',
  step7H2:'🚀 创建模型',step7Suffix:'创建模型',
  clearLabel:'生成前清除现有节点 / 单元 / 材料 / 截面 / 边界条件 / 荷载',
  genBtnLbl:'⚽ 开始生成足球结构',
  logInit:'▶ 请按"创建模型"按钮开始。',noticeTitle:'画面未更新？',
  hintShortcutTitle:'快捷键',hintShortcutDesc:'<code>Ctrl + A</code><br>全选 → 刷新视图',
  hintMouseTitle:'鼠标',hintMouseDesc:'在视口中：<br>滚轮或拖拽',
  hintMenuTitle:'菜单',hintMenuDesc:'View → Fit All',
  toAnalBtnLbl:'执行分析 →',
  traceName3dEdge:'梁单元 (90)',traceName3dNode:'节点 (60)',
  traceSup:'支承节点 ({n})',traceLoad:'荷载节点 ({n})',
  step8H2anal:'⚡ 执行分析',step8H2result:'📊 分析结果',
  badgeWait:'⏸ 等待中',badgeRun:'🔄 分析中...',badgeDone:'✅ 完成',badgeErr:'❌ 错误',
  runAnalBtnLbl:'🔬 开始分析',
  alogInit:'▶ 请按"开始分析"按钮。（请先完成模型创建）',
  lblLoadCase:'荷载工况',
  tabReact:'反力',tabDisp:'位移',tabMember:'内力',
  tabShear:'剪力',tabMoment:'弯矩',tabTorsion:'扭矩',tabStress:'应力比 / DCR',
  startOverBtn:'🔄 重新开始',freeTrialBtn:'免费试用申请 →',
  logInit5:'初始化中...',logCleared:'已清除现有数据',logMat15:'创建材料中...',
  logMatFail:'材料创建失败：{msg}',logMatOk:'材料：{name}',logSect25:'创建截面中...',
  logSectFail:'截面创建失败：{msg}',logSectOk:'截面：{name} ({h}×{b} mm)',
  logNode38:'创建节点中...',logNodeFail:'节点创建失败：{msg}',logNodeOk:'已创建 {n} 个节点',
  logElem52:'创建单元中...',logElemFail:'单元创建失败：{msg}',logElemOk:'已创建 {n} 个梁单元',
  logBC65:'创建边界条件中...',logBCFail:'边界条件创建失败：{msg}',
  logBCOk:'边界条件：{n} 个节点（{label}）',logBCNone:'边界条件：无',
  logLoad78:'创建荷载中...',logLC:'荷载工况：[{type}] {name}',
  logSWFail:'自重创建失败：{msg}',logSWOk:'  自重（{dir} × {val}）',
  logNLFail:'节点荷载创建失败：{msg}',logNLOk:'  节点荷载：{n} 个节点（Fz={fz} N）',
  logNLNone:'  节点荷载：无目标节点',logDone:'完成！',
  logModelOk:'🎉 {name} 模型创建完成！',logError:'错误：{msg}',
  alogUnits:'设置单位 (N, MM)...',alogUnitsOk:'单位设置完成',
  alogRunning:'分析执行中...（等待完成）',analFailed:'分析失败',alogDone:'分析完成',
  alogFetchLC:'获取结果中（{n} 个荷载工况）...',
  alogReact:'获取反力中...',alogReactOk:'反力：{n} 条数据',alogReactNone:'无反力数据',
  alogDisp:'获取位移中...',alogDispOk:'位移：{n} 条数据',alogDispNone:'无位移数据',
  alogForce:'获取内力 (BEAMFORCE)...',alogForceOk:'内力：{n} 条数据',alogForceNone:'无内力数据',
  alogStress:'获取应力比 (BEAMSTRESS)...',alogStressOk:'应力比：{n} 条数据',
  alogStressNone:'无应力比数据（未执行设计验算时为正常）',
  alogStressSkip:'应力比获取跳过（{msg}）',alogAllDone:'🎉 分析及结果获取完成！',
  alogError:'错误：{msg}',
  statSupNodeCount:'支承节点数',chartReact:'反力 Fz (N) — 各支承节点',xaxisNode:'节点编号',
  statMaxDisp:'最大合成位移 (mm)',chartDisp:'Dz 位移 Top 20 (mm)',
  statMemberCount:'构件数',chartAxial:'轴力 Fx Top 20 (N)',xaxisElem:'单元编号',
  statMaxShear:'最大剪力合力 (N)',chartShear:'剪力 Top 20 (|Fy|)',yaxisShear:'剪力 (N)',
  chartMoment:'弯矩 Top 20 (|Mz|)',yaxisMoment:'弯矩 (N·mm)',
  noTorsion:'无扭矩数据 (Mx)',chartTorsion:'扭矩 Mx Top 20 (N·mm)',
  noStress:'无应力比数据（未执行设计验算或 API 不支持）',
  statMaxStress:'最大应力比',statAvgStress:'平均应力比',
  statOverStress:'超限构件 (>1.0)',statTotalMember:'构件总数',
  stressName:'应力比',chartStress:'应力比 Top 20',yaxisStress:'应力比',
  supFixLabel:'固定端 (Dx Dy Dz Rx Ry Rz)',supPinLabel:'铰接 (Dx Dy Dz)',
  supRolLabel:'滚动支承-Z (Dz)',supCustLabel:'自定义：',
  sumSupLabel:'<b>支承：</b>',sumNodeAuto:'自动（最底部节点）',sumNodeManual:'手动 — ',
  sumNodeLabel:'<b>节点选择：</b>',
  step9Headline:'立即免费体验<br>MIDAS！',
  step9Sub:'就像您刚才亲手创建并分析的足球结构，<br>用 MIDAS Gen NX · Civil NX 将您的设计构想化为现实。',
  step9CTA:'免费试用申请 →',
  tf1Desc:'建筑结构专业分析软件<br>非线性・抗震・性能设计<br>API 自动化工作流程',
  tf2Desc:'桥梁・土木结构分析软件<br>三维・施工阶段・PSC 分析<br>API 自动化工作流程',
  tf3Desc:'通过 REST API 自动完成<br>模型创建・分析执行・结果获取<br>全流程自动化',
  tsStep1:'申请免费试用',tsStep2:'电子邮件验证',tsStep3:'下载软件',tsStep4:'立即开始使用',
  tlBtn1:'🎁 免费试用申请',tlBtn2:'🌐 MIDAS 官方网站',
  step9BackBtn:'← 上一步',
},
th:{
  pageTitle:'สัมผัสเทคโนโลยี MIDAS API ล่าสุดไปกับฟุตบอลโลก 2026',
  headerH1:'สัมผัสเทคโนโลยี MIDAS API ล่าสุดไปกับฟุตบอลโลก 2026',
  headerMeta:'การสร้างโครงสร้างทรงตัดยี่สิบหน้า (ลูกฟุตบอล) อัตโนมัติ &nbsp;·&nbsp; ผู้พัฒนา: Dennis &nbsp;·&nbsp; v{ver} (อัปเดต {date})',
  step1:'เลือกผลิตภัณฑ์',step2:'เชื่อมต่อ API',step3:'พารามิเตอร์',step4:'เงื่อนไขขอบเขต',step5:'น้ำหนักบรรทุก',
  step6:'ตัวอย่าง 3D',step7:'สร้างโมเดล',step8:'วิเคราะห์',step9:'ทดลองใช้ฟรี',
  sidebarEyebrow:'ประสบการณ์ MIDAS API',
  sidebarH2:'เดโมนี้<br>ทำอะไรได้บ้าง?',
  sidebarDesc:'<strong style="color:#c7d2fe">ใช้ Open API ของ MIDAS Gen NX / Civil NX</strong><br>สร้างโครงสร้างลูกฟุตบอล (ทรงตัดยี่สิบหน้า) ได้โดยตรงในเบราว์เซอร์ —<br>ตั้งแต่ <strong style="color:#c7d2fe">สร้างอัตโนมัติ → วิเคราะห์ → แสดงผลลัพธ์</strong><br>ทีละขั้นตอน',
  flow1:'① เลือกผลิตภัณฑ์',flow2:'② เชื่อมต่อ API',flow3:'③ พารามิเตอร์',flow4:'④ ขอบเขต&amp;น้ำหนัก',
  flow5:'⑤ ตัวอย่าง 3D',flow6:'⑥ สร้างโมเดล',flow7:'⑦ รันการวิเคราะห์',flow8:'⑧ ดูผลลัพธ์',
  nudgeTitle:'ยังไม่มีข้อมูลการเชื่อมต่อ API?',
  nudgeDesc:'สมัครทดลองใช้ฟรีตอนนี้แล้วรับ API Key ได้ทันที!',
  nudgeBtn:'สมัครทดลองใช้ฟรี →',
  wcEyebrow:'ฟุตบอลโลก FIFA 2026 · อเมริกาเหนือ-กลาง',
  wcH2:'🏆 พิธีปิด &amp; รอบชิงชนะเลิศ',
  wcLabel1:'พิธีปิด',wcDate1:'19 กรกฎาคม 2026 (อา.)',
  wcKst1:'จัดก่อนรอบชิงชนะเลิศ',wcVenue:'MetLife Stadium, East Rutherford รัฐนิวเจอร์ซีย์ สหรัฐฯ',
  wcLabel2:'รอบชิงชนะเลิศ',wcDate2:'20 ก.ค. 2026 (จ.) 02:00 ICT',
  wcKst2:'เวลาท้องถิ่น: 19 ก.ค. (อา.) 15:00 ET',
  cdLabel:'⏱ นับถอยหลังสู่รอบชิงชนะเลิศ (เวลาไทย ICT)',cdInit:'กำลังคำนวณ...',cdKickoff:'รอบชิงเริ่มแล้ว!🎉',
  step1H2:'🎯 เลือกซอฟต์แวร์ของคุณ',step1Desc:'เลือกซอฟต์แวร์ MIDAS เพื่อสร้างโครงสร้างลูกฟุตบอล',
  genNXDesc:'ซอฟต์แวร์วิเคราะห์โครงสร้างอาคาร<br>ไม่เชิงเส้น・ต้านแผ่นดินไหว・ตามสมรรถนะ<br>เวิร์กโฟลว์อัตโนมัติด้วย API',
  genNXBadge:'โครงสร้างอาคาร',
  civilNXDesc:'ซอฟต์แวร์วิเคราะห์สะพานและงานโยธา<br>3 มิติ・ขั้นตอนการก่อสร้าง・วิเคราะห์ PSC<br>เวิร์กโฟลว์อัตโนมัติด้วย API',
  civilNXBadge:'สะพาน・โยธา',
  confirmBtn:'ยืนยันการเลือก →',selectFirst:'กรุณาเลือกซอฟต์แวร์ก่อน',
  step2H2Suffix:'การเชื่อมต่อ API',mapiPlaceholder:'กรอก MAPI Key ของคุณ',baseUrlLabel:'Base URL (กรอกค่าเริ่มต้นอัตโนมัติ แก้ไขได้)',
  showHideKey:'แสดง/ซ่อนคีย์',testConn:'ทดสอบการเชื่อมต่อ →',backBtn:'← ย้อนกลับ',
  enterBothAlert:'กรุณากรอก MAPI Key ของคุณ',testingConn:'กำลังทดสอบการเชื่อมต่อ...',
  connSuccess:'✅ เชื่อมต่อสำเร็จ! กำลังไปยังขั้นตอนถัดไป',
  connFail:'❌ ตรวจสอบการเชื่อมต่อล้มเหลว: {status}',
  connDisconnected:'❌ {prog} ไม่ได้เปิด/เชื่อมต่ออยู่ กรุณาเปิดโปรแกรมแล้วลองใหม่ (คีย์ถูกต้อง)',
  connMismatch:'❌ ผลิตภัณฑ์ไม่ตรงกัน: คีย์นี้สำหรับ {key} (ที่เลือกอยู่: {sel}) กรุณาเปลี่ยนการเลือกผลิตภัณฑ์',
  connError:'❌ ข้อผิดพลาดการเชื่อมต่อ: {msg}',
  step3H2:'📐 พารามิเตอร์โครงสร้าง',secSize:'ขนาดโครงสร้าง',lblRadius:'รัศมี (mm)',
  lblCx:'จุดศูนย์กลาง X (mm)',lblCy:'จุดศูนย์กลาง Y (mm)',lblCz:'จุดศูนย์กลาง Z (mm)',
  secMaterial:'วัสดุ (เหล็ก)',lblMatName:'ชื่อวัสดุ',lblElast:'โมดูลัสยืดหยุ่น (MPa)',
  lblPoisn:'อัตราส่วนปัวซอง',lblDen:'ความหนาแน่น (N/mm³)',
  secSection:'หน้าตัด (สี่เหลี่ยมผืนผ้า)',lblSectName:'ชื่อหน้าตัด',lblSectH:'ความสูง H (mm)',lblSectB:'ความกว้าง B (mm)',
  nextBtn:'ถัดไป →',
  step4H2:'🔒 เงื่อนไขขอบเขต (จุดรองรับ)',secSupNode:'เลือกโหนดจุดรองรับ',
  nodeAuto:'อัตโนมัติ (โหนดล่างสุด)',nodeManual:'กำหนดเอง (กรอกโดยตรง)',
  nodeAutoDesc:'เลือก<strong>โหนดที่อยู่ล่างสุด</strong>โดยอัตโนมัติตามรัศมีและจุดศูนย์กลาง Z',
  lblManualNodes:'หมายเลขโหนด (คั่นด้วยจุลภาค เช่น 1,5,9)',secSupType:'ประเภทจุดรองรับ',
  supFixName:'ยึดแน่น',supPinName:'บานพับ (พิน)',supRolName:'ลูกกลิ้ง (Z)',supCustName:'กำหนดเอง',
  supCustDesc:'เลือก DOF',selectDOF:'เลือก DOF ที่จะยึด',
  dofDx:'Dx (เลื่อนแกน X)',dofDy:'Dy (เลื่อนแกน Y)',dofDz:'Dz (เลื่อนแกน Z)',
  dofRx:'Rx (หมุนแกน X)',dofRy:'Ry (หมุนแกน Y)',dofRz:'Rz (หมุนแกน Z)',
  step5H2:'⬇️ ตั้งค่าน้ำหนักบรรทุก',addLCBtn:'+ เพิ่มกรณีน้ำหนัก',previewBtn:'ดูตัวอย่าง →',
  lcBadgeLabel:'กรณีน้ำหนัก',deleteBtn:'ลบ',
  lblLCName:'<label>ชื่อกรณีน้ำหนัก</label>',lblLCType:'<label>ประเภทน้ำหนัก</label>',
  lcOptUser:'USER (กำหนดเอง)',lcOptD:'D (น้ำหนักคงที่)',lcOptL:'L (น้ำหนักจร)',
  lcOptW:'W (น้ำหนักลม)',lcOptE:'E (น้ำหนักแผ่นดินไหว)',lcLoadKind:'ชนิดของน้ำหนัก',
  tagSW:'น้ำหนักตัวเอง',tagNL:'น้ำหนักที่โหนด',
  lblDirection:'<label>ทิศทาง</label>',swDirZ:'-Z (แรงโน้มถ่วง)',
  lblScale:'<label>ตัวคูณ</label>',nlAll:'ทุกโหนด',nlBottom:'โหนดล่างสุด',nlManual:'กรอกเอง',
  lblNLNodes:'<label style="font-size:.79rem;color:#666">หมายเลขโหนด (คั่นด้วยจุลภาค)</label>',
  step6H2:'🔍 ตัวอย่าง 3D',metricNodes:'โหนด',metricBeams:'ชิ้นส่วนคาน',metricRadius:'รัศมี (mm)',
  genModelBtn:'สร้างโมเดล →',
  step7H2:'🚀 สร้างโมเดล',step7Suffix:'การสร้างโมเดล',
  clearLabel:'ล้างโหนด / ชิ้นส่วน / วัสดุ / หน้าตัด / เงื่อนไขขอบเขต / น้ำหนัก เดิมก่อนสร้าง',
  genBtnLbl:'⚽ เริ่มสร้างลูกฟุตบอล',
  logInit:'▶ กดปุ่ม "สร้างโมเดล" เพื่อเริ่ม',noticeTitle:'หน้าจอไม่อัปเดต?',
  hintShortcutTitle:'คีย์ลัด',hintShortcutDesc:'<code>Ctrl + A</code><br>เลือกทั้งหมด → รีเฟรชมุมมอง',
  hintMouseTitle:'เมาส์',hintMouseDesc:'ในวิวพอร์ต:<br>เลื่อนหรือลาก',
  hintMenuTitle:'เมนู',hintMenuDesc:'View → Fit All',
  toAnalBtnLbl:'รันการวิเคราะห์ →',
  traceName3dEdge:'ชิ้นส่วน (90)',traceName3dNode:'โหนด (60)',
  traceSup:'โหนดจุดรองรับ ({n})',traceLoad:'โหนดน้ำหนัก ({n})',
  step8H2anal:'⚡ รันการวิเคราะห์',step8H2result:'📊 ผลการวิเคราะห์',
  badgeWait:'⏸ รอดำเนินการ',badgeRun:'🔄 กำลังวิเคราะห์...',badgeDone:'✅ เสร็จสิ้น',badgeErr:'❌ ข้อผิดพลาด',
  runAnalBtnLbl:'🔬 เริ่มวิเคราะห์',
  alogInit:'▶ กดปุ่ม "เริ่มวิเคราะห์" (ต้องสร้างโมเดลก่อน)',
  lblLoadCase:'กรณีน้ำหนัก',
  tabReact:'แรงปฏิกิริยา',tabDisp:'การเคลื่อนตัว',tabMember:'แรงภายในชิ้นส่วน',
  tabShear:'แรงเฉือน',tabMoment:'โมเมนต์ดัด',tabTorsion:'โมเมนต์บิด',tabStress:'อัตราส่วนความเค้น / DCR',
  startOverBtn:'🔄 เริ่มใหม่',freeTrialBtn:'สมัครทดลองใช้ฟรี →',
  logInit5:'กำลังเริ่มต้น...',logCleared:'ล้างข้อมูลเดิมเรียบร้อย',logMat15:'กำลังสร้างวัสดุ...',
  logMatFail:'สร้างวัสดุล้มเหลว: {msg}',logMatOk:'วัสดุ: {name}',logSect25:'กำลังสร้างหน้าตัด...',
  logSectFail:'สร้างหน้าตัดล้มเหลว: {msg}',logSectOk:'หน้าตัด: {name} ({h}×{b} mm)',
  logNode38:'กำลังสร้างโหนด...',logNodeFail:'สร้างโหนดล้มเหลว: {msg}',logNodeOk:'สร้าง {n} โหนด',
  logElem52:'กำลังสร้างชิ้นส่วน...',logElemFail:'สร้างชิ้นส่วนล้มเหลว: {msg}',logElemOk:'สร้างชิ้นส่วนคาน {n} ชิ้น',
  logBC65:'กำลังสร้างเงื่อนไขขอบเขต...',logBCFail:'สร้างเงื่อนไขขอบเขตล้มเหลว: {msg}',
  logBCOk:'เงื่อนไขขอบเขต: {n} โหนด ({label})',logBCNone:'เงื่อนไขขอบเขต: ไม่มี',
  logLoad78:'กำลังสร้างน้ำหนัก...',logLC:'กรณีน้ำหนัก: [{type}] {name}',
  logSWFail:'สร้างน้ำหนักตัวเองล้มเหลว: {msg}',logSWOk:'  น้ำหนักตัวเอง ({dir} × {val})',
  logNLFail:'สร้างน้ำหนักที่โหนดล้มเหลว: {msg}',logNLOk:'  น้ำหนักที่โหนด: {n} โหนด (Fz={fz} N)',
  logNLNone:'  น้ำหนักที่โหนด: ไม่มีโหนดเป้าหมาย',logDone:'เสร็จสิ้น!',
  logModelOk:'🎉 สร้างโมเดล {name} เสร็จสมบูรณ์!',logError:'ข้อผิดพลาด: {msg}',
  alogUnits:'กำลังตั้งค่าหน่วย (N, MM)...',alogUnitsOk:'ตั้งค่าหน่วยเรียบร้อย',
  alogRunning:'กำลังรันการวิเคราะห์... (รอจนเสร็จ)',analFailed:'การวิเคราะห์ล้มเหลว',alogDone:'วิเคราะห์เสร็จสิ้น',
  alogFetchLC:'กำลังดึงผลลัพธ์ ({n} กรณีน้ำหนัก)...',
  alogReact:'กำลังดึงแรงปฏิกิริยา...',alogReactOk:'แรงปฏิกิริยา: {n} แถว',alogReactNone:'ไม่มีข้อมูลแรงปฏิกิริยา',
  alogDisp:'กำลังดึงการเคลื่อนตัว...',alogDispOk:'การเคลื่อนตัว: {n} แถว',alogDispNone:'ไม่มีข้อมูลการเคลื่อนตัว',
  alogForce:'กำลังดึงแรงภายใน (BEAMFORCE)...',alogForceOk:'แรงภายใน: {n} แถว',alogForceNone:'ไม่มีข้อมูลแรงภายใน',
  alogStress:'กำลังดึงอัตราส่วนความเค้น (BEAMSTRESS)...',alogStressOk:'อัตราส่วนความเค้น: {n} แถว',
  alogStressNone:'ไม่มีข้อมูลอัตราส่วนความเค้น (ปกติหากยังไม่ได้ตรวจสอบการออกแบบ)',
  alogStressSkip:'ข้ามการดึงอัตราส่วนความเค้น ({msg})',alogAllDone:'🎉 วิเคราะห์และดึงผลลัพธ์เสร็จสมบูรณ์!',
  alogError:'ข้อผิดพลาด: {msg}',
  statSupNodeCount:'จำนวนโหนดจุดรองรับ',chartReact:'แรงปฏิกิริยา Fz (N) ตามโหนดจุดรองรับ',xaxisNode:'หมายเลขโหนด',
  statMaxDisp:'การเคลื่อนตัวรวมสูงสุด (mm)',chartDisp:'การเคลื่อนตัว Dz Top 20 (mm)',
  statMemberCount:'จำนวนชิ้นส่วน',chartAxial:'แรงตามแกน Fx Top 20 (N)',xaxisElem:'หมายเลขชิ้นส่วน',
  statMaxShear:'แรงเฉือนรวมสูงสุด (N)',chartShear:'แรงเฉือน Top 20 (|Fy|)',yaxisShear:'แรงเฉือน (N)',
  chartMoment:'โมเมนต์ดัด Top 20 (|Mz|)',yaxisMoment:'โมเมนต์ (N·mm)',
  noTorsion:'ไม่มีข้อมูลโมเมนต์บิด (Mx)',chartTorsion:'โมเมนต์บิด Mx Top 20 (N·mm)',
  noStress:'ไม่มีข้อมูลอัตราส่วนความเค้น (ยังไม่ตรวจสอบการออกแบบ หรือ API ไม่รองรับ)',
  statMaxStress:'อัตราส่วนความเค้นสูงสุด',statAvgStress:'อัตราส่วนความเค้นเฉลี่ย',
  statOverStress:'ชิ้นส่วนเกินขีดจำกัด (>1.0)',statTotalMember:'จำนวนชิ้นส่วนทั้งหมด',
  stressName:'อัตราส่วนความเค้น',chartStress:'อัตราส่วนความเค้น Top 20',yaxisStress:'อัตราส่วนความเค้น',
  supFixLabel:'ยึดแน่น (Dx Dy Dz Rx Ry Rz)',supPinLabel:'บานพับ (Dx Dy Dz)',
  supRolLabel:'ลูกกลิ้ง-Z (Dz)',supCustLabel:'กำหนดเอง: ',
  sumSupLabel:'<b>จุดรองรับ:</b> ',sumNodeAuto:'เลือกโหนดล่างสุดอัตโนมัติ',sumNodeManual:'กรอกเอง — ',
  sumNodeLabel:'<b>การเลือกโหนด:</b> ',
  step9Headline:'ทดลองใช้ MIDAS<br>ฟรีตอนนี้เลย!',
  step9Sub:'เช่นเดียวกับโครงสร้างลูกฟุตบอลที่คุณเพิ่งสร้างและวิเคราะห์<br>เปลี่ยนไอเดียของคุณให้เป็นจริงด้วย MIDAS Gen NX · Civil NX',
  step9CTA:'สมัครทดลองใช้ฟรี →',
  tf1Desc:'ซอฟต์แวร์วิเคราะห์โครงสร้างอาคาร<br>ไม่เชิงเส้น・ต้านแผ่นดินไหว・ตามสมรรถนะ<br>เวิร์กโฟลว์อัตโนมัติด้วย API',
  tf2Desc:'ซอฟต์แวร์วิเคราะห์สะพานและงานโยธา<br>3 มิติ・ขั้นตอนก่อสร้าง・วิเคราะห์ PSC<br>เวิร์กโฟลว์อัตโนมัติด้วย API',
  tf3Desc:'ตั้งแต่สร้างโมเดลผ่าน REST API<br>จนถึงรันวิเคราะห์และดึงผลลัพธ์<br>อัตโนมัติได้อย่างสมบูรณ์',
  tsStep1:'สมัครทดลองใช้ฟรี',tsStep2:'ยืนยันอีเมล',tsStep3:'ดาวน์โหลดซอฟต์แวร์',tsStep4:'เริ่มใช้งานได้ทันที',
  tlBtn1:'🎁 สมัครทดลองใช้ฟรี',tlBtn2:'🌐 เว็บไซต์ทางการ MIDAS',
  step9BackBtn:'← ย้อนกลับ',
}
};
